### ISSUE TITLE
getting typescript compilation error

### ISSUE THREAD

**Issue by sharathk2u** [havsar/node-ts-cache#13] opened 2019-12-18 05:59 UTC
Hi. I've installed the module but i get the attached issue when I tried to build my app.

![Screenshot 2019-12-18 at 11 22 38 AM](https://user-images.githubusercontent.com/11290603/71059713-8ee79800-2189-11ea-81cf-816355136102.png)

Please do let me know on how to resolve this.

FYI:
node: v10.16.0 
tsc: 3.7.2

**Comment by marcoslin** [comment] 2019-12-19 21:28
Basically, the problem is cause by `strict=true` in your tsconfig.json.  I also use this option so I am having the sample problem. 

If you want to keep `strict` flag in your project, the code needs to be changed from source:

1. Deploy compiled code instead of raw ts code.  In this case, we can ignore any error in the `node_modules` using the `skipLibCheck`  
1. Fix the source code so that it will compile with `strict` flag set

**Comment by havsar** [comment] 2020-11-25 14:38
Thanks @marcoslin 

I will consider this in the next release (4.0.0).

**Comment by GuyKh** [comment] 2020-12-30 10:18
Could be related to this, but I'm getting:
```


node_modules/node-ts-cache/src/strategy/caching/abstract.base.strategy.ts:9:12 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.

9     public async abstract getItem<T>(key: string): Promise<T>;
             ~~~~~

node_modules/node-ts-cache/src/strategy/caching/abstract.base.strategy.ts:11:12 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.

11     public async abstract setItem(key: string, content: any, options: any): Promise<void>;
              ~~~~~

node_modules/node-ts-cache/src/strategy/caching/abstract.base.strategy.ts:13:12 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.

13     public async abstract clear(): Promise<void>;
```

**Comment by havsar** [comment] 2020-12-31 05:20
@GuyKh It is related. There were some changes in the new tsc. This issues will be fixed in 4.0.0.

**Comment by havsar** [comment] 2020-12-31 12:44
@sharathk2u  @marcoslin @GuyKh 
Please check with newest version (4.2.2) if possible.

**Comment by GuyKh** [comment] 2020-12-31 13:07
@havsar 
Still no -- now getting the following:

```

src/app.ts:16:10 - error TS2305: Module '"../node_modules/node-ts-cache/dist"' has no exported member 'ExpirationStrategy'.

16 import { ExpirationStrategy, MemoryStorage } from "node-ts-cache";
            ~~~~~~~~~~~~~~~~~~

src/app.ts:16:30 - error TS2305: Module '"../node_modules/node-ts-cache/dist"' has no exported member 'MemoryStorage'.

16 import { ExpirationStrategy, MemoryStorage } from "node-ts-cache";
                                ~~~~~~~~~~~~~
```

**Comment by havsar** [comment] 2020-12-31 15:51
@GuyKh V4 has breaking changes. Please see the [docs](https://github.com/havsar/node-ts-cache) for the current usage examples.

**Comment by GuyKh** [comment] 2021-01-03 07:01
@havsar looks good after the modifications

**Closed** 2021-01-05 07:50 UTC
Labels: bug
